version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'retreater'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - dev-db-postgres:/var/lib/postgresql/data/

volumes:
  dev-db-postgres:
