-- AlterTable
ALTER TABLE `Order` ADD COLUMN `errorReason` VARCHAR(191),
    MODIFY `state` ENUM('CREATED', 'PENDING', 'PARTIALLY_CONFIRMED', 'CONFIRMED', 'DECLINED', 'CANCELLED', 'ERRORED') NOT NULL DEFAULT 'CREATED';
